clinic/urls.py
from django.urls import path, include
from .views import (
    PatientList,
    PrescriptionList,
    DoctorList,
    PatientDetail,
    DoctorDetail,
    PrescriptionDetail,
    ClinicView,
    BookList,
    BookDetail,
    DoctorCreateView, PrescriptionCreateView, PatientCreateView, BookCreateView
)

app_name = 'clinic'

urlpatterns = [
    path('', ClinicView.as_view(), name='dashboard'),
    path('patient/', PatientList.as_view(), name='patient-list'),
    path('prescription/', PrescriptionList.as_view(), name='prescription-list'),
    path('doctor/', DoctorList.as_view(), name='doctor-list'),
    path('book/', BookList.as_view(), name='book-list'),
    path('book/<int:pk>/', BookDetail.as_view(), name='book-detail'),
    path('doctor/<int:pk>/', DoctorDetail.as_view(), name='doctor-detail'),
    path('patient/<int:pk>/', PatientDetail.as_view(), name='patient-detail'),
    path('prescription/<int:pk>/', PrescriptionDetail.as_view(), name='prescription-detail'),
    path('create-doctor/', DoctorCreateView.as_view(), name='doctor-create'),
    path('create-prescription/', PrescriptionCreateView.as_view(), name='prescription-create'),
    path('create-patient/', PatientCreateView.as_view(), name='patient-create'),
    path('create-book/', BookCreateView.as_view(), name='book-create'),

]

optical/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from clinic.views import IndexView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('clinic/', include('clinic.urls', namespace='clinic')),
    path('', IndexView.as_view(), name='index'),



] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <!-- Fa -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <title>{% block title %} Base {% endblock title %}</title>
    <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  </head>
  <body>

       <!-- NAVBAR -->
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark p-0">
        <div class="container">
            <a href="{% url 'clinic:dashboard' %}" class="navbar-brand"><i class="fa fa-eye" aria-hidden="true"></i>

Optics Clinic</a>
            <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
{#                    <li class="nav-item px-2">#}
{#                        <a href="index.html" class="nav-link active">Dashboard</a>#}
{#                    </li>#}
                    <li class="nav-item px-2">
                        <a href="{% url 'clinic:patient-list' %}" class="nav-link">Patients</a>
                    </li>
                    <li class="nav-item px-2">
                        <a href="{% url 'clinic:doctor-list' %}" class="nav-link">Doctors</a>
                    </li>
                    <li class="nav-item px-2">
                        <a href="{% url 'clinic:prescription-list' %}" class="nav-link">Prescriptions</a>
                    </li>
                    <li class="nav-item px-2">
                        <a href="{% url 'clinic:book-list' %}" class="nav-link">Bookings</a>
                    </li>
                </ul>

                <ul class="navbar-nav ml-auto">
                    <li class="nav-item dropdown mr-3">
                         <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
                             <i class="fa fa-user"></i> Welcome back timi
                         </a>
                         <div class="dropdown-menu">
                             <a href="profile.html" class="dropdown-item">
                                 <i class="fa fa-user-circle"></i> Profile
                             </a>
                             <a href="settings.html" class="dropdown-item">
                                <i class="fa fa-gear"></i> Settings
                            </a>
                         </div>
                    </li>
                    <li class="nav-item">
                        <a href="login.html" class="nav-link">
                            <i class="fa fa-user-times"></i>
                            Logout
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <header id="main-header" class="py-2 bg-grey text-white" style="background-color:grey;">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h1> {% block head %} Dashboard {% endblock head %}</h1>
                </div>
            </div>
        </div>
    </header>







        {% block content %}

        {% endblock content %}


    <footer id="main-footer" class="bg-dark text-white mt-5 p-5" >
        <div class="container">
            <div class="row">
                <div class="col">
                    <p class="lead text-center">Copyright &copy; 2018 Optics</p>
                    <p class="lead text-center mt-3">Designed with <i class="fa fa-heart"></i> <a class="text-white" href="http://twitter.com/rhotimee"> by rhotimee</a> </p>
                </div>
            </div>
        </div>

    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/index.html
{% extends "base.html" %}

{% block title %} Home {% endblock title %}

{% block content %}

    <div class="container">Hi Everybody</div>

{% endblock content %}

templates/pagination.html
{% if is_paginated %}
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
           <a href="?page={{page.previous_page_number}}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>
{% endif %}